### ISSUE TITLE
我在cxkitty那边添加了argparse登录

### ISSUE THREAD

**Issue by guowang23333** [2061360308/CxKitty#2]
你这个可以参考一下我那边对于dialog的更改，做到输入账号密码科目，达到真正的输入账号密码科目自己跑，顺便说一下查记录这个。。。其实完全可以搞request请求的，用文字来表述进度，更加直观一点

**Comment by 2061360308** [comment]
我发现的问题是，服务器环境不稳定，就是说，有时候你搭建的时候会遇到很多奇怪问题，有时间花4-5个小时才能搞定。为了自己刷个课，感觉真的不值。或许长期运行加用户多了比较划算，但该开源项目也不让盈利。。。所以就很是鸡肋
