### ISSUE TITLE
为啥部署完成，输入手机号进入后看到是的很多none，求解答

### ISSUE THREAD

**Issue by jamiescou** [2061360308/CxKitty#3]
<img width="1413" alt="image" src="https://github.com/2061360308/CxKitty/assets/15727736/86156c69-f880-4b2c-88e5-1e81d3c2845b">
<img width="1402" alt="image" src="https://github.com/2061360308/CxKitty/assets/15727736/4b993dca-d43a-4515-b5cb-6ed2eb1e1429">

**Comment by 2061360308** [comment]
不怎么维护了哈，去原仓库可以找到人家的命令行版本，那个应该在维护。这种抓取接口类型的项目长时间不维护就会报废了。😀，主要有次我自己要用的时候在服务器上安装命令行版本的，装了四五个小时最后还是没效果（阿里云服务器的问题），然后我就觉着服务器上安装不确定因素太多了，太浪费时间，不如直接开油猴脚本稳定方便，所以就懒得维护了。
