### ISSUE TITLE
在termux无法运行

### ISSUE THREAD

**Issue by xmexg** [2061360308/CxKitty#6]
![Screenshot_2024-10-24-18-47-16-160_com.termux.jpg](https://github.com/user-attachments/assets/64c9e775-eba1-4c2b-af0e-2c368df7d7f5)

**Comment by 2061360308** [comment]
目前没有办法帮你解决这个问题，但是如果你只想在安卓设备上进行刷课的话，可以参考这个讨论内容，作者详细记录了他在安卓手机上使用termux刷学习通课程的过程。（步骤还是有些烦琐，我也尝试过使用kiwi浏览器安装油猴后跑OCS网课助手，但是很遗憾没办法工作）

https://github.com/Samueli924/chaoxing/discussions/372

**Comment by 2061360308** [comment]
这是我关于安卓上进行学习通自动刷课的最新尝试，可以参考

https://github.com/Samueli924/chaoxing/discussions/372#discussioncomment-11095435

**Comment by d4renk** [comment]
poetry在termux运行有问题，你应该去看看poetry的issues，或者尝试没有使用poetry的项目，比如https://github.com/Samueli924/chaoxing。
你也可以使用kiwi 安装ocs脚本。

**Comment by xmexg** [comment]
管用，谢谢大家
